# This is a basic workflow to help you get started with Actions
name: Jest Testing
# Controls when the action will run.
on:

  push:
    branches:
    - development
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: install puppeteer libraries
        run: |  
          sudo apt-get update
          sudo apt-get install -y libgbm1
      - uses: actions/checkout@v2
      - name: install jest
        run: npm i jest
      - name: Run Test
        run: npm test
